---
- name: Ansible Facts
  hosts: localhost

  tasks:
#Edit values.j2 to correctly display the corresponding ansible_fact
    - name: Template Out Values
      template:
        src: values.j2


#####DON’T EDIT BELOW THIS LINE

    - name: TURN ON GREEN
      include_role:
        name: hue
        tasks_from: green.yaml