---
- name: ENSURE APACHE IS INSTALLED
  hosts: linux
  become: yes
  tasks:

    - name: ENSURE APACHE IS INSTALLED
      yum:
        name: httpd
        state: installed
      register: http_install

#####DON’T EDIT BELOW THIS LINE

- name: update solution
  import_playbook: "solution.yml"
