---
- name: ENSURE APACHE IS INSTALLED
  hosts: linux
  become: yes
  tasks:
#Challenge: Update task below
#Ensure Apache is installed
    - name: ENSURE APACHE IS INSTALLED
      yum:
        name: httpd
        state: installed
      register: http_install

#####DON’T EDIT BELOW THIS LINE

- name: update solution
  vars:
    bulb1: true
  import_playbook: "solution.yml"
