---
- name: ENSURE VLANS ARE PRESENT ON ARISTA DEVICE
  hosts: eos
  gather_facts: no
  vars:
    vlans:
      - id: 100
        name: vlan-100
      - id: 200
        name: vlan-200
      - id: 300
        name: vlan-300

#Challenge: Update the task below
#Utilize the {{ vlans }} variable to push the correct configuration
  tasks:
    - name: ENSURE 3 VLANS ARE PRESENT
      eos_vlan:


#####DON’T EDIT BELOW THIS LINE

- name: update solution
  vars:
    bulb3: true
  import_playbook: "solution.yml"
