---
- name: ENSURE THAT THE L3 INTERFACE IS CONFIGURED ON CISCO DEVICE
  hosts: ios
  gather_facts: no
  vars:
    loopback:
      number: 200
      ip: 200.200.200.200
      mask: 255.255.255.255

#Challenge: Update the task below
#Ensure the Loopback Interface is configured using the {{ loopback }} variable
  tasks:
    - name: ENSURE LOOPBACK INTERFACE EXISTS
      ios_


#####DON’T EDIT BELOW THIS LINE

- name: update solution
  vars:
    lab: net-l3
  import_playbook: "solution.yml"
