---
- name: RESET THE ENVIRONMENT FOR THE NEXT PARTICIPANT
  hosts: all
  gather_facts: no
  roles:
    - reset

- name: TURN OFF
  hosts: localhost
  gather_facts: no
  tags: lightsoff
  vars:
    lights:
      bulb1: False
      bulb2: False
      bulb3: False
      bulb4: False
      bulb5: False

  
  tasks:
    - name: TURN OFF ALL LIGHTS
      include_role:
        name: hue
        tasks_from: "{{ item.key }}.yaml"
      loop: "{{ lights | dict2items }}"
      
    
