---
- name: RHEL workshop_type
  hosts: localhost
  become: true
  gather_facts: no
  connection: local
  tasks:
    - name: running encrypted load-letter logic
      debug:
        msg: "running solution algorithm delta niner 33283x83"

    - set_fact:
       lights:
         bulb1: "{{ bulb1 | default(lights.bulb1,true)}}"
         bulb2: "{{ bulb2 | default(lights.bulb2,true)}}"
         bulb3: "{{ bulb3 | default(lights.bulb3,true)}}"
         bulb4: "{{ bulb4 | default(lights.bulb4,true)}}"
         bulb5: "{{ bulb5 | default(lights.bulb5,true)}}"

    - name: push structured data to groupvars
      copy:
        content: "{{ lights | to_nice_yaml}}"
        dest: "{{playbook_dir}}/group_vars/all.yml"

    - debug:
        var: lights

    - name: TURN ON ORANGE
      include_role:
        name: website

    - name: TURN ON ORANGE
      include_role:
        name: hue
        tasks_from: orange.yaml
