---
- name: RHEL workshop_type
  hosts: localhost
  become: true
  gather_facts: no
  connection: local
  tasks:
    - name: running encrypted load-letter logic
      debug:
        msg: "running solution algorithm delta niner 33283x83"

    - set_fact:
       lights:
         bulb1: "{{ bulb1 | default(lights.bulb1,true)}}"
         bulb2: "{{ bulb2 | default(lights.bulb2,true)}}"
         bulb3: "{{ bulb3 | default(lights.bulb3,true)}}"
         bulb4: "{{ bulb4 | default(lights.bulb4,true)}}"
         bulb5: "{{ bulb5 | default(lights.bulb5,true)}}"

    - name: push structured data to groupvars
      copy:
        content: |
          lights:
            bulb1: {{ lights.bulb1 }}
            bulb2: {{ lights.bulb2 }}
            bulb3: {{ lights.bulb3 }}
            bulb4: {{ lights.bulb4 }}
            bulb5: {{ lights.bulb5 }}
        dest: "{{playbook_dir}}/group_vars/all.yml"

    - debug:
        var: lights

    - name: TURN ON ORANGE
      include_role:
        name: website

    - name: TURN ON THE BULBS
      include_role:
        name: hue
        tasks_from: "{{ item.key }}.yaml"
      loop: "{{ lights | dict2items }}"
        
