---
- name: RHEL workshop_type
  hosts: localhost
  become: true
  gather_facts: no
  connection: local
  tasks:
    - name: running encrypted load-letter logic
      debug:
        msg: "running solution algorithm delta niner 33283x83"

    - name: TURN ON ORANGE
      include_role:
        name: website

    - name: TURN ON ORANGE
      include_role:
        name: hue
        tasks_from: orange.yaml
