---
- name: ENSURE IIS FEATURES ARE ON
  hosts: windows
  tasks:

#Challenge: Update the below task
#Ensure IIS is installed WITH Sub features and management tools
    - name: ENSURE IIS FEATURES ARE ON
      win_feature:
        name: Web-Server
        state: running
      register: win_feature
      ignore_errors: yes

#####DON’T EDIT BELOW THIS LINE

- name: check solution
  vars:
    lab: windows
  import_playbook: "solution.yml"
