---
- name: ENSURE IIS FEATURES ARE ON
  hosts: windows
  become: yes
  tasks:

#Challenge: Update the below task 
#Ensure IIS is installed WITH Sub features and management tools
    - name: ENSURE IIS FEATURES ARE ON
      win_feature:
        name: Web-Server
        state: installed
      register: win_feature

#####DON’T EDIT BELOW THIS LINE

    - name: TURN ON BLUE
      include_role:
        name: hue
        tasks_from: blue.yaml
        
