- debug: var=lights.bulb2
  
- set_fact:
    state: on
  when: lights.bulb2|bool

- set_fact:
    state: off
  when: not lights.bulb2|bool


- set_fact:
    on_state: "{{ on_state | combine({'xy':  blue} )}}"

- debug: var=state

- uri:
    url: "http://{{hue_host}}/api/{{hue_user}}/lights/2/state"
    method: PUT
    body: ' {{on_state|to_json}}'
  when: state 
  delegate_to: localhost
  
  



- uri:
    url: "http://{{hue_host}}/api/{{hue_user}}/lights/2/state"
    method: PUT
    body: ' {{off_state|to_json}}'
  when: not state 
  delegate_to: localhost
